return {
  "nvim-treesitter/nvim-treesitter",
  	opts = {
  		ensure_installed = {
        "json",
        "html",
        "css",
        "scss",
        "javascript",
        "typescript",
        "svelte",
        "tsx",
        "yaml",
        "prisma",
        "markdown",
        "markdown_inline",
        "qraphql",
        "bash",
        "dockerfile",
        "gitignore",
        "query",
        "vimdoc",
        "c",
        "cpp",
        "swift",
        "vim",
        "lua",
        "vimdoc",
        "glsl",
        "objc",
        "toml"
  		},
  	},
}
