return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "json",
        "html",
        "css",
        "scss",
        "javascript",
        "typescript",
        "svelte",
        "tsx",
        "yaml",
        "prisma",
        "markdown",
        "markdown_inline",
        -- "qraphql",
        "bash",
        "dockerfile",
        "gitignore",
        "query",
        "c",
        "cpp",
        "swift",
        "glsl",
        "objc",
        "toml",
      },
    },
    -- incremental_selection = {
    --   enable = true,
    --   keymaps = {
    --     init_selection = "gnn",
    --     node_incremental = "grn",
    --     scope_incremental = "grc",
    --     node_decremental = "grm",
    --   },
    -- },
  },
}
